## need to add server.  entries to enable HTTPS with SSL keystore, replace "????" with correct entries

server.port=8443
server.ssl.key-alias=globalRainArtemis
server.ssl.key-store-password=cs305Project2
server.ssl.key-store=artemisKeystore.jks
server.ssl.key-store-type=JKS
 
